package com.example.ifanow.controllers;

import com.example.ifanow.entities.dtos.EventRequest;
import com.example.ifanow.services.RegisterEventService;
import com.example.ifanow.utils.ValidationUtil;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.ValidationUtils;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * This class is reponsible for catching/ingesting all the events generated by ifanow app
 *
 * @author akashverma
 * @version 1.0.0
 */
@RestController
@RequestMapping("/")
public class CatchEventController {

    private static final Logger LOGGER = LoggerFactory.getLogger(CatchEventController.class);

    @Autowired
    private RegisterEventService registerEventService;

    @PostMapping(value = "register/event")
    public void registerEvent(@RequestBody EventRequest eventRequest) {
        try {
            ValidationUtil.assertNotNull(eventRequest.getUserId());
            registerEventService.register(eventRequest);
        } catch (IllegalArgumentException e) {
            LOGGER.info("Exception in input " + e);
            throw new IllegalArgumentException();
        }catch (Exception e){
            LOGGER.debug("Exception while registering event: " + e);
        }
    }
}
